### test
# author : hey
# parameter :
# description : test
# error code : 400
### test
GET {{host}}/v1/lecture
Accept: application/json
Content-Type: application/json

### Add One Lecture
# author : hey
# parameter :
# description : 강의 하나 생성하기
# error code : 400
### test
POST {{host}}/v1/lecture
Accept: application/json
Content-Type: application/json

{
  "name": "웹 개발",
  "category": "웹",
  "teacher_id" : 1,
  "introduction": "웹 개발 강의입니다",
  "fee": 45000
}